spring:
  application:
    name: UserRegistrationService
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: joaoalves2002
mail:
  host: http://www.user-regist.com
  port: 8080